### ISSUE TITLE
Pixels are gamma-corrected instead of linear

### ISSUE THREAD

**Issue by lnicola** [meh/rust-picto#2]
In the `palette` library, the `Rgb` type represents linear values, which `Srgb` is used for gamma-corrected pixels. `picto`, however, when used as in the sample, will return sRGB values into an `Rgb` structure, requiring the following dance:

``` rust
    let img2 = picto::read::from_path::<Rgb<f32>, f32, _>(&Path::new("foo.jpg")).unwrap();
    for (_, _, pixel) in img.pixels() {
        let rgb: Rgb<f32> = pixel.get();
        let srgb = Srgb::new(rgb.red, rgb.green, rgb.blue);
        let rgb: Rgb<f32> = Rgb::from(srgb);
        // ...
    }
```

Note that `picto::read::from_path::<Srgb<f32>, f32, _>` does not work, probably because of how the pixel type is constrained.

**Comment by meh** [comment]
Yeah I was wondering about that, as far as you know which formats (supported by picto) always return buffers in sRGB space?

Also the second type should really be `u8` and not `f32`, but that's beside the problem for this issue.

**Comment by lnicola** [comment]
> Yeah I was wondering about that, as far as you know which formats (supported by picto) always return buffers in sRGB space?

Actually I don't think there is a standard for that, but most images made to be displayed on a computer are in the sRGB space. One can find other colour spaces in the wild (e.g. Adobe RGB JPEGs saved by DSLRs configured to do so), but the only way to recognize those is to look at the EXIF tag. I'm not familiar with the XYZ format, but it looks like a DEFLATE-compressed bitmap.

Anyway, `image` returns RGBA values, but `picto`'s API makes the pixel type more visible. Compare:

``` rust
    for (_, _, pixel) in img.pixels() {
        let srgb = Srgb::new_u8(pixel[0], pixel[1], pixel[2]);
        let rgb = Rgb::from(srgb);
        // ...
}
```

which seems quite reasonable to me. I'd say it's fine to let the user choose with the appropriate type argument.

> Also the second type should really be u8 and not f32, but that's beside the problem for this issue.

Right. In the beginning I was a bit confused about those.

**Comment by meh** [comment]
> Actually I'm not sure and I don't think there is a standard for that, but most images made to be displayed on a computer are in the sRGB space. One can find other colour spaces in the wild (e.g. Adobe RGB JPEGs saved by DSLRs configured to do so), but the only way to recognize those is to look at the EXIF tag.

That is annoying.

Also I see the problem with using `Srgb` directly, basically the decoders are designed to always return the generic `Buffer` requested, this means the `Pixel` type of the `Buffer` has to be convertible from the buffer types provided internally by the decoder.

For instance the PNG decoder can return `Luma`, `Lumaa`, `Rgb` and `Rgba` native buffers, which means the `Pixel` type you want your `Buffer` in has to be convertible from those.

Sadly `Srgb` doesn't implement `From<Luma>` and `From<Lumaa>` which means the types aren't compatible, and `read::from_path::<Srgb, u8, _>` will fail to compile.

Since as you say the actual color-space is as it was unknown as far as the decoding crates I'm using are concerned, I think the current situation is fine enough, I just need to add more documentation.

For instance, this code is equivalent to yours:

``` rust
let img2 = picto::read::from_path::<Rgb, u8, _>("foo.jpg").unwrap();
let img2 = img2.convert::<Srgb, u8>();
```

At that point `img2` will be in `Srgb`.

**Comment by meh** [comment]
To avoid the whole fanfare though, the best solution would be for `palette` to implement the missing `From` implementations.

**Comment by meh** [comment]
Also to further expand on that, both the read/decode and write/encode parts are designed this way to avoid copies/conversions/reallocations when they aren't really needed.

The `image` crate solves it by having an `enum DynamicImage` which contains the buffers for `Luma`, `Lumaa`, `Rgb` and `Rgba`, but that limits it to those 4 color spaces, while `palette` has many more and users might want to implement additional `Pixel` types or whatever.

So it's a matter of compile time knowledge of buffer types over runtime knowledge of buffer times, with performance sprinkled in.

Personally I found that I always ended up using specific pixel colors, and dealing with `DynamicImage` wasn't nice at all, so I ended up with this design.

An alternative to solve this problem would be to have my own internal `From` and `Into` types specifically for `Pixel`, and a blanket impl to standard `From` and `Into` to bridge the gap, but I'm not so sure about the advantages of that.

Do you have any thoughts on the matter?

**Comment by meh** [comment]
Ok, I added a `convert_with` method to `Buffer` and all supported views, this allows much shorter conversion and avoids useless roundtrips.

``` rust
use picto;
use picto::color::{Rgb, Srgb};

let image = picto::read::from_path::<Rgb, u8, _>("foo.jpg").unwrap().convert_with::<Rgb, u8, _>(|p| Srgb::from(p).into());
```

This will give you a `Buffer<Rgb, u8, Vec<u8>>` that's been converted from sRGB color space.

**Comment by lnicola** [comment]
Thanks for the commit, but I think it might be somewhat misleading.

Actually, the first example should be

``` rust
let image = picto::read::from_path::<Rgb, u8, _>("foo.jpg").unwrap().convert_with::<Rgb, f32, _>(|p| Srgb::new(p.red, p.green, p.blue).into());
```

because `Srgb::from(rgb)` will perform a color space conversion. Using `u8` as the converted buffer type leads to weird differences that almost look like rounding errors.

I haven't tried the second example, but I believe it has the same color space conversion issue.

**Comment by meh** [comment]
@lnicola true that, I didn't consider precision errors.

``` rust
let image = picto::read::from_path::<Rgb, u8, _>("foo.jpg").unwrap()
    .convert_with::<Rgb, f32, _>(|p| Srgb::from(p).into());
```

Like you said that should do what you want.

**Comment by lnicola** [comment]
@meh No, `Srgb::from(p)` is different from `Srgb::new(p.red, p.green, p.blue)`. The first one assumes that `p` is in linear RGB, which is not true in this case. So your proposed code produces wrong values.

**Comment by meh** [comment]
Ahh makes sense, I updated the README with notes on how to deal with it, could you check if it's correct please?

**Comment by lnicola** [comment]
Looks great, thanks!

**Comment by lnicola** [comment]
Umm. The pixel type is still wrong in the documentation.

**Comment by meh** [comment]
The loaded `Buffer` channel as `u8` is correct, what you as `f32` is the channel for the sRGB converted buffer, hence why it's `convert_with::<Rgb, f32, _>`, the final result is a `Buffer<Rgb, f32, Vec<f32>>`.

**Comment by lnicola** [comment]
No, I meant here https://github.com/meh/rust-picto/blob/915a14a67a85c20d318e8aa72abef83b1571a3dd/src/buffer/buffer.rs#L342 and in the other places.

**Comment by meh** [comment]
Oh those, thanks, fixing 🐼
